### ISSUE TITLE
ItemCollectorConfiguration.json doesn't have the list of locations

### ISSUE THREAD

**Issue by kp-g-mok** [oranisagu/SDV-FarmAutomation#26]
Minor documentation issue.

From the FAQ:
Q: How do I add other locations to look for machines?

A: The configuration file now contains a full list of locations. You can add any location you'd like, but be careful, if you place a machine or chest where a NPC walks through, the machine will get destroyed (this has nothing to do with this mod and is just the games normal behaviour)

But this is what's in ItemCollectorConfiguration.json
`/* the names of the game locations where machines are searched for.  */
  "LocationsToSearch": "Farm, Greenhouse, FarmHouse, FarmCave",`

**Comment by oranisagu** [comment]
added in v0.1.9, I didn't make a release just for the config changes so the latest release didn't contain the updated config until now.
